### ISSUE TITLE
Error when extracting tables from a PDF

### ISSUE THREAD

**Issue by Awerito** [li-rongzhi/pdf2table#2]
Has in the example with my pdf:
```py
from pdf2table import Driver

# Initialize the driver
driver = Driver()

# Extract tables from a PDF
# which returns a list of dataframes
tables = driver.extract_tables("sample.pdf")
```
I got the following error when running:
```
Extracting tables from page 1
/home/***/sandbox/env/lib/python3.10/site-packages/pdf2table/table/processing/bordered_tables/cells/identification.py:17: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  .rename({col: f"{col}_" for col in df_h_lines.columns})
/home/***/sandbox/env/lib/python3.10/site-packages/pdf2table/table/processing/bordered_tables/cells/deduplication.py:24: PerformanceWarning: Determining the column names of a LazyFrame requires resolving its schema, which is a potentially expensive operation. Use `LazyFrame.collect_schema().names()` to get the column names without this warning.
  .rename({col: f"{col}_" for col in df_cells.columns})
Extracting tables from page 2
Extracting tables from page 3
Extracting tables from page 4
Extracting tables from page 5
Extracting tables from page 6
Extracting tables from page 7
Extracting tables from page 8
Traceback (most recent call last):
  File "/home/***/sandbox/readpdf.py", line 5, in <module>
    tables = driver.extract_tables("./UB0730.pdf")
  File "/home/***/sandbox/env/lib/python3.10/site-packages/pdf2table/driver.py", line 44, in extract_tables
    tables_in_page = self.tatr.get_tables(value)
  File "/home/***/sandbox/env/lib/python3.10/site-packages/pdf2table/tatr/__init__.py", line 168, in get_tables
    table_list = self.process_table_images(images)
  File "/home/***/sandbox/env/lib/python3.10/site-packages/pdf2table/tatr/__init__.py", line 163, in process_table_images
    df, data = self.apply_ocr(cell_coordinates, image_processed)
  File "/home/***/sandbox/env/lib/python3.10/site-packages/pdf2table/tatr/__init__.py", line 154, in apply_ocr
    return df, data
UnboundLocalError: local variable 'df' referenced before assignment
```
If I could get any help please.

**Comment by rngzhi** [comment]
Thanks for your feedback. Actually this bug has been fixed in the codebase, but I forget to upload the new package. I just updated on pypi. You may try out the new version now. Please let me know if it works.

**Comment by Awerito** [comment]
It works perfectly, thanks!
